### ISSUE TITLE
https://chmura.ztm.rzeszow.pl/ cannot be opened

### ISSUE THREAD

**Issue by IlyaAndr** [MKuranowski/RzeszowGTFS#1]
Hello!
The original server doesn't work anymore but data is available at https://otwartedane.erzeszow.pl/dataset/rozklad-jazdy-transxchange . What do you think about using this one?

**Comment by MKuranowski** [comment]
Thanks, I was looking for a replacement of the TransXChange files. It looks like the new endpoint you provided actually has the same files, so it should be an easy fix.
